/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI;

import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author mandalore
 */
public class CreateObservationPanel extends javax.swing.JPanel {
    
    private Application application;

    /**
     * Creates new form CreateObservationPanel
     */
    public CreateObservationPanel() {
        initComponents();
    }
    
    CreateObservationPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldId = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBloodPressure = new javax.swing.JTextField();
        saveObservationBtn = new javax.swing.JButton();
        bloodPressureLabel = new javax.swing.JLabel();
        createObservationDescriptionLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        idLabel.setText("id");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 20, -1));

        temperatureLabel.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        temperatureLabel.setText("temperature");
        add(temperatureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        fieldId.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        fieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdActionPerformed(evt);
            }
        });
        add(fieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        fieldTemperature.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        fieldTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTemperatureActionPerformed(evt);
            }
        });
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        fieldBloodPressure.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        fieldBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBloodPressureActionPerformed(evt);
            }
        });
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        saveObservationBtn.setBackground(new java.awt.Color(204, 255, 204));
        saveObservationBtn.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        saveObservationBtn.setText("Save Observation");
        saveObservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveObservationBtnActionPerformed(evt);
            }
        });
        add(saveObservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        bloodPressureLabel.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        bloodPressureLabel.setText("blood pressure");
        add(bloodPressureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        createObservationDescriptionLabel.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        createObservationDescriptionLabel.setForeground(new java.awt.Color(255, 255, 102));
        createObservationDescriptionLabel.setText("Enter Patient Vital Signs Here");
        add(createObservationDescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 340, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdActionPerformed

    private void fieldTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTemperatureActionPerformed

    private void fieldBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBloodPressureActionPerformed

    private void saveObservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveObservationBtnActionPerformed
        // TODO add your handling code here:
        
        VitalSignHistory vsh = this.application.getVitalSignHistory();
        
        String id = fieldId.getText();
        String temperature = fieldTemperature.getText();
        String bloodPressure = fieldTemperature.getText();
        
        vsh.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure), Double.valueOf(temperature));
        
        JOptionPane.showMessageDialog(null, "observation added successfully!");
    }//GEN-LAST:event_saveObservationBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodPressureLabel;
    private javax.swing.JLabel createObservationDescriptionLabel;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveObservationBtn;
    private javax.swing.JLabel temperatureLabel;
    // End of variables declaration//GEN-END:variables
}
