/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package UI;

import Model.Application;



/**
 *
 * @author mandalore
 */
public class MainIFrame extends javax.swing.JFrame {
    
    private Application application;
    /**
     * Creates new form MainIFrame
     */
    public MainIFrame() {
        initComponents();
        
        this.application = new Application();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        ViewVitalSignButton = new javax.swing.JButton();
        ViewMedicineCatalogBtn = new javax.swing.JButton();
        AssignMedicineBtn = new javax.swing.JButton();
        createObservationBtn = new javax.swing.JButton();
        DisplayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setBackground(new java.awt.Color(255, 51, 0));
        ControlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewVitalSignButton.setText("Vital Sign History");
        ViewVitalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVitalSignButtonActionPerformed(evt);
            }
        });
        ControlPanel.add(ViewVitalSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 130, -1));

        ViewMedicineCatalogBtn.setText("Medicine catalog");
        ViewMedicineCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMedicineCatalogBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(ViewMedicineCatalogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 119, -1, -1));

        AssignMedicineBtn.setText("Assign medicine");
        AssignMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignMedicineBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(AssignMedicineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 130, -1));

        createObservationBtn.setText("Observation");
        createObservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObservationBtnActionPerformed(evt);
            }
        });
        ControlPanel.add(createObservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 130, -1));

        jSplitPane1.setLeftComponent(ControlPanel);

        DisplayPanel.setBackground(new java.awt.Color(0, 255, 51));
        DisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setRightComponent(DisplayPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createObservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObservationBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateObservationPanel(this.application));
    }//GEN-LAST:event_createObservationBtnActionPerformed

    private void ViewVitalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVitalSignButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ViewVitalSignHistoryPanel(this.application));

    }//GEN-LAST:event_ViewVitalSignButtonActionPerformed

    private void ViewMedicineCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMedicineCatalogBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedicineCatalogPanel(this.application));

    }//GEN-LAST:event_ViewMedicineCatalogBtnActionPerformed

    private void AssignMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignMedicineBtnActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AssignMedicinePanel(this.application));

    }//GEN-LAST:event_AssignMedicineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainIFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignMedicineBtn;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton ViewMedicineCatalogBtn;
    private javax.swing.JButton ViewVitalSignButton;
    private javax.swing.JButton createObservationBtn;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
