/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI;

import Model.Application;

/**
 *
 * @author mandalore
 */
public class MedicineCatalogPanel extends javax.swing.JPanel {

    Application application;

    /**
     * Creates new form MedicineCatalogPanel
     */
    public MedicineCatalogPanel() {
        initComponents();
    }

    MedicineCatalogPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldMedName = new javax.swing.JTextField();
        fieldDosage = new javax.swing.JTextField();
        addMedicineDetails = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMedNameActionPerformed(evt);
            }
        });
        add(fieldMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 280, -1));

        fieldDosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDosageActionPerformed(evt);
            }
        });
        add(fieldDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 280, -1));

        addMedicineDetails.setText("Add New Medicine Details");
        addMedicineDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicineDetailsActionPerformed(evt);
            }
        });
        add(addMedicineDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMedicineDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicineDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicineDetailsActionPerformed

    private void fieldMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMedNameActionPerformed

    private void fieldDosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDosageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedicineDetails;
    private javax.swing.JTextField fieldDosage;
    private javax.swing.JTextField fieldMedName;
    // End of variables declaration//GEN-END:variables
}
