/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author mandalore
 */
public class CreateJPanel extends javax.swing.JPanel {

    private DeliveryPackage delPackage;

    private Boolean validate = false;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();

        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pdName = new javax.swing.JTextField();
        pdID = new javax.swing.JTextField();
        pdPrice = new javax.swing.JTextField();
        pkWeight = new javax.swing.JTextField();
        pkID = new javax.swing.JTextField();
        pnLabel = new javax.swing.JLabel();
        pidLabel = new javax.swing.JLabel();
        ppLabel = new javax.swing.JLabel();
        pkwLabel = new javax.swing.JLabel();
        pkidLabel = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        customerID = new javax.swing.JTextField();
        cnmLabel = new javax.swing.JLabel();
        cidLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        savePrdtBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 51));
        setFont(new java.awt.Font("Menlo", 0, 14)); // NOI18N

        pdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdNameActionPerformed(evt);
            }
        });

        pdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdIDActionPerformed(evt);
            }
        });

        pdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdPriceActionPerformed(evt);
            }
        });

        pkWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkWeightActionPerformed(evt);
            }
        });

        pkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkIDActionPerformed(evt);
            }
        });

        pnLabel.setForeground(new java.awt.Color(255, 51, 51));
        pnLabel.setText("Product Name");

        pidLabel.setForeground(new java.awt.Color(255, 51, 51));
        pidLabel.setText("Product ID");

        ppLabel.setForeground(new java.awt.Color(255, 51, 51));
        ppLabel.setText("Product Price");

        pkwLabel.setForeground(new java.awt.Color(255, 51, 51));
        pkwLabel.setText("Package Weight");

        pkidLabel.setForeground(new java.awt.Color(255, 51, 51));
        pkidLabel.setText("Package ID");

        customerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameFocusLost(evt);
            }
        });
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });

        customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDActionPerformed(evt);
            }
        });

        cnmLabel.setForeground(new java.awt.Color(255, 51, 51));
        cnmLabel.setText("Customer Name");

        cidLabel.setForeground(new java.awt.Color(255, 51, 51));
        cidLabel.setText("Customer ID");

        saveButton.setForeground(new java.awt.Color(255, 51, 51));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        savePrdtBtn.setForeground(new java.awt.Color(255, 51, 51));
        savePrdtBtn.setText("SAVE");
        savePrdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePrdtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pidLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pdID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(pdName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ppLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savePrdtBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cnmLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pkidLabel)
                    .addComponent(pkwLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pkID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pkWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(444, 444, 444))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnLabel)
                            .addComponent(pkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pkidLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pkWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pkwLabel)))
                    .addComponent(pidLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppLabel)
                    .addComponent(pdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(savePrdtBtn)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnmLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidLabel))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(534, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdNameActionPerformed

    private void pkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkIDActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String id = pkID.getText();
        String weight = pkWeight.getText();

        String customerNm = customerName.getText();
        String customerId = customerID.getText();

        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerNm);

        if (validate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void pdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdIDActionPerformed

    private void pdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdPriceActionPerformed

    private void pkWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pkWeightActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDActionPerformed

    private void savePrdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePrdtBtnActionPerformed
        // TODO add your handling code here:
        String prodtId = pdID.getText();
        String prodtNm = pdName.getText();
        String prodtPr = pdPrice.getText();

        Product product = this.delPackage.createProduct(Integer.valueOf(prodtId), prodtNm, Double.valueOf(prodtPr));

        JOptionPane.showMessageDialog(null, "Added Product");

    }//GEN-LAST:event_savePrdtBtnActionPerformed

    private void customerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFocusLost
        // TODO add your handling code here:
        System.out.println(customerName.getText() + " -- the customer name");
        String name = customerName.getText();

        if (name.isEmpty()) {
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_customerNameFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cidLabel;
    private javax.swing.JLabel cnmLabel;
    private javax.swing.JTextField customerID;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField pdID;
    private javax.swing.JTextField pdName;
    private javax.swing.JTextField pdPrice;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextField pkID;
    private javax.swing.JTextField pkWeight;
    private javax.swing.JLabel pkidLabel;
    private javax.swing.JLabel pkwLabel;
    private javax.swing.JLabel pnLabel;
    private javax.swing.JLabel ppLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton savePrdtBtn;
    // End of variables declaration//GEN-END:variables
}
