/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.ContactInformation;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Tugume William Mutara
 */
public class MainJFrame extends javax.swing.JFrame {

    private Person person;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();

        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        rightPanel = new javax.swing.JPanel();
        viewNUID = new javax.swing.JLabel();
        viewCollegeName = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewName = new javax.swing.JLabel();
        viewCStreetName = new javax.swing.JLabel();
        viewCAptNo = new javax.swing.JLabel();
        viewCCityState = new javax.swing.JLabel();
        viewCZipCode = new javax.swing.JLabel();
        viewPStreetName = new javax.swing.JLabel();
        viewPCityState = new javax.swing.JLabel();
        viewPAptNo = new javax.swing.JLabel();
        viewPZipCode = new javax.swing.JLabel();
        viewPPhNo = new javax.swing.JLabel();
        viewPEmail = new javax.swing.JLabel();
        viewOPhNo = new javax.swing.JLabel();
        viewOEmail = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        viewStreet = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        fieldCollegeName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldcStreet = new javax.swing.JTextField();
        fieldcAptNo = new javax.swing.JTextField();
        fieldcCityState = new javax.swing.JTextField();
        fieldcZipCode = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldpStreetName = new javax.swing.JTextField();
        fieldpCityState = new javax.swing.JTextField();
        fieldpAptNo = new javax.swing.JTextField();
        fieldpZipCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldpPhNo = new javax.swing.JTextField();
        fieldpEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldoPhNo = new javax.swing.JTextField();
        fieldoEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewNUID.setText("NUID");

        viewCollegeName.setText("College Name");

        viewLastName.setBackground(new java.awt.Color(255, 51, 51));
        viewLastName.setText("LastName");

        viewName.setText("FirstName");

        viewCStreetName.setText("Street");

        viewCAptNo.setText("AptNo");

        viewCCityState.setText("City/State");

        viewCZipCode.setText("ZipCode");

        viewPStreetName.setText("Street");

        viewPCityState.setText("CIty/State");

        viewPAptNo.setText("AptNo");

        viewPZipCode.setText("ZipCode");

        viewPPhNo.setText("phone number");

        viewPEmail.setText("Email");

        viewOPhNo.setText("phone number");

        viewOEmail.setText("Email");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewLastName)
                            .addComponent(viewCollegeName)
                            .addComponent(viewNUID))
                        .addContainerGap(585, Short.MAX_VALUE))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCCityState)
                            .addComponent(viewName)
                            .addComponent(viewCStreetName)
                            .addComponent(viewCZipCode)
                            .addComponent(viewCAptNo)
                            .addComponent(viewPStreetName)
                            .addComponent(viewPCityState)
                            .addComponent(viewPAptNo)
                            .addComponent(viewPZipCode)
                            .addComponent(viewPPhNo)
                            .addComponent(viewPEmail)
                            .addComponent(viewOPhNo)
                            .addComponent(viewOEmail))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewNUID)
                .addGap(20, 20, 20)
                .addComponent(viewCollegeName)
                .addGap(18, 18, 18)
                .addComponent(viewLastName)
                .addGap(18, 18, 18)
                .addComponent(viewName)
                .addGap(56, 56, 56)
                .addComponent(viewCStreetName)
                .addGap(26, 26, 26)
                .addComponent(viewCCityState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCAptNo)
                .addGap(18, 18, 18)
                .addComponent(viewCZipCode)
                .addGap(55, 55, 55)
                .addComponent(viewPStreetName)
                .addGap(32, 32, 32)
                .addComponent(viewPCityState)
                .addGap(18, 18, 18)
                .addComponent(viewPAptNo)
                .addGap(18, 18, 18)
                .addComponent(viewPZipCode)
                .addGap(49, 49, 49)
                .addComponent(viewPPhNo)
                .addGap(18, 18, 18)
                .addComponent(viewPEmail)
                .addGap(36, 36, 36)
                .addComponent(viewOPhNo)
                .addGap(18, 18, 18)
                .addComponent(viewOEmail)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(rightPanel);

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewStreet.setForeground(new java.awt.Color(255, 0, 0));

        fieldCollegeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCollegeNameActionPerformed(evt);
            }
        });

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        fieldcStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcStreetActionPerformed(evt);
            }
        });

        fieldcAptNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcAptNoActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("CURRENT ADDRESS");

        jLabel2.setText("PERMANENT ADDRESS");

        fieldpAptNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldpAptNoActionPerformed(evt);
            }
        });

        jLabel3.setText("PERSONAL CONTACT");

        jLabel4.setText("OFFICE CONTACT");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldoPhNo)
                            .addComponent(fieldoEmail)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldpEmail)
                            .addComponent(fieldpPhNo)
                            .addComponent(fieldpZipCode)
                            .addComponent(fieldpStreetName)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldcStreet)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCollegeName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNUID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftPanelLayout.createSequentialGroup()
                                .addComponent(fieldcCityState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewStreet))
                            .addComponent(fieldcAptNo))
                        .addGap(48, 48, 48))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(fieldcZipCode)
                        .addContainerGap())
                    .addComponent(fieldpCityState)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(fieldpAptNo))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldcStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewStreet))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(fieldcCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldcAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldcZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldpStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldpCityState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldpAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldpZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldpPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldoPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(saveButton))
        );

        jSplitPane2.setLeftComponent(leftPanel);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String collegeName = fieldCollegeName.getText();
        String nUID = fieldNUID.getText();
        
        String cStreet = fieldcStreet.getText();
        String cAptNo = fieldcAptNo.getText();
        String cCityState = fieldcCityState.getText();
        String cZipCode = fieldcZipCode.getText();
        
        String pStreet = fieldpStreetName.getText();
        String pAptNo = fieldpAptNo.getText();
        String pCityState = fieldpCityState.getText();
        String pZipCode = fieldpZipCode.getText();
        
        String pPhNo = fieldpPhNo.getText();
        String pEmail = fieldpEmail.getText();
        
        String oPhNo = fieldoPhNo.getText();
        String oEmail = fieldoEmail.getText();
        
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(collegeName);
        this.person.setnUID(nUID);

        //setting the cuurent Address object.
        Address currentAddress = this.person.getCurrentAddress();
        currentAddress.setStreetName(cStreet);
        currentAddress.setAptNo(cAptNo);
        currentAddress.setCityState(cCityState);
        currentAddress.setZipCode(cZipCode);

        //setting the permanent address object.
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreetName(pStreet);
        permanentAddress.setAptNo(pAptNo);
        permanentAddress.setCityState(pCityState);
        permanentAddress.setZipCode(pZipCode);
        
        ContactInformation officeContact = this.person.getOfficeContact();
        officeContact.setPhoneNumber(oPhNo);
        officeContact.setEmail(oEmail);
        
        ContactInformation personalContact = this.person.getPersonalContact();
        personalContact.setPhoneNumber(pPhNo);
        personalContact.setEmail(pEmail);
        

        JOptionPane.showMessageDialog(null, "Saved Successfully!");

        //method to display information on panel.
        display();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void fieldcStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcStreetActionPerformed

    private void fieldCollegeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCollegeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCollegeNameActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldcAptNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcAptNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcAptNoActionPerformed

    private void fieldpAptNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldpAptNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldpAptNoActionPerformed

    private void display() {
        //display person class attributes
        viewName.setText(this.person.getFirstName());   
        viewCollegeName.setText(this.person.getCollegeName());
        viewLastName.setText(this.person.getLastName());
        viewNUID.setText(this.person.getnUID());
        
        //display currentAddress of person.
        viewCStreetName.setText(this.person.getCurrentAddress().getStreetName());
        viewCAptNo.setText(this.person.getCurrentAddress().getAptNo());
        viewCCityState.setText(this.person.getCurrentAddress().getCityState());
        viewCZipCode.setText(this.person.getCurrentAddress().getZipCode());
        
        //display permanentAddress of person.
        viewPStreetName.setText(this.person.getPermanentAddress().getStreetName());
        viewPAptNo.setText(this.person.getPermanentAddress().getAptNo());
        viewPCityState.setText(this.person.getPermanentAddress().getCityState());
        viewPZipCode.setText(this.person.getPermanentAddress().getZipCode());
        
        viewPPhNo.setText(this.person.getPersonalContact().getPhoneNumber());
        viewPEmail.setText(this.person.getPersonalContact().getEmail());
        
        viewOPhNo.setText(this.person.getPersonalContact().getPhoneNumber());
        viewOEmail.setText(this.person.getPersonalContact().getEmail());
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldcAptNo;
    private javax.swing.JTextField fieldcCityState;
    private javax.swing.JTextField fieldcStreet;
    private javax.swing.JTextField fieldcZipCode;
    private javax.swing.JTextField fieldoEmail;
    private javax.swing.JTextField fieldoPhNo;
    private javax.swing.JTextField fieldpAptNo;
    private javax.swing.JTextField fieldpCityState;
    private javax.swing.JTextField fieldpEmail;
    private javax.swing.JTextField fieldpPhNo;
    private javax.swing.JTextField fieldpStreetName;
    private javax.swing.JTextField fieldpZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel viewCAptNo;
    private javax.swing.JLabel viewCCityState;
    private javax.swing.JLabel viewCStreetName;
    private javax.swing.JLabel viewCZipCode;
    private javax.swing.JLabel viewCollegeName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewOEmail;
    private javax.swing.JLabel viewOPhNo;
    private javax.swing.JLabel viewPAptNo;
    private javax.swing.JLabel viewPCityState;
    private javax.swing.JLabel viewPEmail;
    private javax.swing.JLabel viewPPhNo;
    private javax.swing.JLabel viewPStreetName;
    private javax.swing.JLabel viewPZipCode;
    private javax.swing.JLabel viewStreet;
    // End of variables declaration//GEN-END:variables
}
