/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI.MangerWorkArea;

import Business.Business;
import Business.UserAccount;
import Customer.Customer;
import Restaurant.DeliveryAgent;
import Service.Order;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mandalore
 */
public class OrderManagementJPanel extends javax.swing.JPanel {
    
    private Business business;
    
    private UserAccount userAccount;
    
    private DefaultTableModel tableModel;

    /**
     * Creates new form OrderManagementPanel
     */
    public OrderManagementJPanel() {
        initComponents();
    }
    
    OrderManagementJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.userAccount = userAccount;
        this.tableModel = (DefaultTableModel) OrderManagementTable.getModel();
        populateDp();
        
        populate();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        assignAgent = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderManagementTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 255, 153));

        assignAgent.setText("assign Agent");
        assignAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignAgentActionPerformed(evt);
            }
        });

        OrderManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "order id", "customer", "delivery agent"
            }
        ));
        jScrollPane1.setViewportView(OrderManagementTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(assignAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(assignAgent)
                .addGap(141, 141, 141))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignAgentActionPerformed
        // TODO add your handling code here:
        DeliveryAgent agent = (DeliveryAgent) jComboBox1.getSelectedItem();
        
        int selectedRow = OrderManagementTable.getSelectedRow();
        
        Order o = (Order) OrderManagementTable.getValueAt(selectedRow, 0);
        o.setDeliveryAgent(agent);
        agent.addDeliveryOrder(o);
        populate();
    }//GEN-LAST:event_assignAgentActionPerformed
    
    public void populate() {
        tableModel.setRowCount(0);
        for (Order o : this.business.getMasterOrderDirectory().getOrderList()) {
            
            Object[] row = new Object[3];
            
            row[0] = o;
            row[1] = o.getCustomer().getPersonId();
            row[2] = o.getDeliveryAgent().getPersonId();
            
            tableModel.addRow(row);
        }
    }
    
    public void populateDp() {
        jComboBox1.removeAllItems();
        
        for (DeliveryAgent d : this.business.getDeliveryAgentDirectory().getDeliveryAgentList()) {
            jComboBox1.addItem(d);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderManagementTable;
    private javax.swing.JButton assignAgent;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
